#!/bin/bash

# Frontend Deployment Script for Travel Agent
# Builds and deploys frontend to S3 + CloudFront

set -e  # Exit on any error

# Configuration
ENVIRONMENT=${1:-dev}
AWS_PROFILE=${2:-bookhood}
STACK_NAME="TravelAgentStack-${ENVIRONMENT}"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_DIR="$PROJECT_ROOT/frontend"

# AWS CLI with profile
AWS_CLI="aws --profile $AWS_PROFILE"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check if AWS CLI is installed
    if ! command -v aws &> /dev/null; then
        log_error "AWS CLI is not installed. Please install it first."
        exit 1
    fi
    
    # Check if Node.js is installed
    if ! command -v node &> /dev/null; then
        log_error "Node.js is not installed. Please install it first."
        exit 1
    fi
    
    # Check if npm is installed
    if ! command -v npm &> /dev/null; then
        log_error "npm is not installed. Please install it first."
        exit 1
    fi
    
    # Check if we're in the right directory
    if [ ! -f "$FRONTEND_DIR/package.json" ]; then
        log_error "Frontend package.json not found. Please run this script from the project root."
        exit 1
    fi
    
    log_success "Prerequisites check passed"
}

# Extract CDK outputs
extract_cdk_outputs() {
    log_info "Extracting CDK stack outputs..."
    
    # Check if stack exists
    if ! $AWS_CLI cloudformation describe-stacks --stack-name "$STACK_NAME" &> /dev/null; then
        log_error "CDK stack '$STACK_NAME' not found. Please deploy the CDK stack first:"
        log_error "  cd cdk && cdk deploy $STACK_NAME --profile $AWS_PROFILE"
        exit 1
    fi
    
    # Extract outputs using AWS CLI
    OUTPUTS=$($AWS_CLI cloudformation describe-stacks --stack-name "$STACK_NAME" --query 'Stacks[0].Outputs' --output json)
    
    # Parse outputs
    FRONTEND_BUCKET=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="FrontendBucketName") | .OutputValue')
    DISTRIBUTION_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="CloudFrontDistributionId") | .OutputValue')
    DISTRIBUTION_DOMAIN=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="CloudFrontDistributionDomainName") | .OutputValue')
    COGNITO_USER_POOL_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="CognitoUserPoolId") | .OutputValue')
    COGNITO_CLIENT_ID=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="CognitoUserPoolClientId") | .OutputValue')
    COGNITO_REGION=$(echo "$OUTPUTS" | jq -r '.[] | select(.OutputKey=="CognitoRegion") | .OutputValue')
    
    # Validate outputs
    if [ "$FRONTEND_BUCKET" = "null" ] || [ -z "$FRONTEND_BUCKET" ]; then
        log_error "Failed to extract frontend bucket name from CDK outputs"
        exit 1
    fi
    
    if [ "$DISTRIBUTION_ID" = "null" ] || [ -z "$DISTRIBUTION_ID" ]; then
        log_error "Failed to extract CloudFront distribution ID from CDK outputs"
        exit 1
    fi
    
    log_success "CDK outputs extracted successfully"
    log_info "Frontend Bucket: $FRONTEND_BUCKET"
    log_info "Distribution ID: $DISTRIBUTION_ID"
    log_info "Distribution Domain: $DISTRIBUTION_DOMAIN"
}

# Generate production environment file
generate_env_file() {
    log_info "Generating .env.production file..."
    
    # Prompt for Agent Core URL if not provided
    if [ -z "$AGENT_CORE_URL" ]; then
        echo -n "Enter Agent Core URL (press Enter for default from .env.development): "
        read AGENT_CORE_URL
        
        if [ -z "$AGENT_CORE_URL" ]; then
            # Extract from .env.development
            if [ -f "$FRONTEND_DIR/.env.development" ]; then
                AGENT_CORE_URL=$(grep "VITE_AGENT_CORE_URL" "$FRONTEND_DIR/.env.development" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
                log_info "Using Agent Core URL from .env.development: $AGENT_CORE_URL"
            else
                log_warning "No Agent Core URL provided and .env.development not found. Using placeholder."
                AGENT_CORE_URL="https://your-agent-core-url.com"
            fi
        fi
    fi
    
    # Create .env.production file
    cat > "$FRONTEND_DIR/.env.production" << EOF
# Production Environment Configuration
# Generated by deploy-frontend.sh at $(date)

VITE_ENVIRONMENT=production
VITE_AGENT_CORE_URL=$AGENT_CORE_URL
VITE_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
VITE_COGNITO_USER_POOL_CLIENT_ID=$COGNITO_CLIENT_ID
VITE_COGNITO_REGION=$COGNITO_REGION

# Production Feature Flags
VITE_ENABLE_ANALYTICS=true
VITE_ENABLE_ERROR_REPORTING=true
VITE_ENABLE_DEBUG_MODE=false
EOF
    
    log_success ".env.production file created"
}

# Build frontend
build_frontend() {
    log_info "Building frontend..."
    
    cd "$FRONTEND_DIR"
    
    # Install dependencies if node_modules doesn't exist
    if [ ! -d "node_modules" ]; then
        log_info "Installing dependencies..."
        npm install
    fi
    
    # Build with production environment
    log_info "Running production build..."
    NODE_ENV=production npm run build
    
    # Verify build output
    if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
        log_error "Build failed - dist directory or index.html not found"
        exit 1
    fi
    
    log_success "Frontend build completed successfully"
}

# Deploy to S3
deploy_to_s3() {
    log_info "Deploying to S3 bucket: $FRONTEND_BUCKET..."
    
    cd "$FRONTEND_DIR"
    
    # Sync files to S3 with appropriate cache headers
    $AWS_CLI s3 sync dist/ "s3://$FRONTEND_BUCKET" \
        --delete \
        --cache-control "public, max-age=31536000" \
        --exclude "*.html" \
        --exclude "service-worker.js" \
        --exclude "manifest.json"
    
    # Upload HTML files and service worker with no-cache headers
    $AWS_CLI s3 sync dist/ "s3://$FRONTEND_BUCKET" \
        --cache-control "public, max-age=0, must-revalidate" \
        --include "*.html" \
        --include "service-worker.js" \
        --include "manifest.json"
    
    log_success "Files deployed to S3 successfully"
}

# Invalidate CloudFront cache
invalidate_cloudfront() {
    log_info "Invalidating CloudFront cache..."
    
    INVALIDATION_ID=$($AWS_CLI cloudfront create-invalidation \
        --distribution-id "$DISTRIBUTION_ID" \
        --paths "/*" \
        --query 'Invalidation.Id' \
        --output text)
    
    log_info "Invalidation created with ID: $INVALIDATION_ID"
    log_info "Waiting for invalidation to complete..."
    
    $AWS_CLI cloudfront wait invalidation-completed \
        --distribution-id "$DISTRIBUTION_ID" \
        --id "$INVALIDATION_ID"
    
    log_success "CloudFront cache invalidation completed"
}

# Main deployment function
main() {
    log_info "Starting frontend deployment for environment: $ENVIRONMENT"
    log_info "Stack name: $STACK_NAME"
    echo
    
    check_prerequisites
    extract_cdk_outputs
    generate_env_file
    build_frontend
    deploy_to_s3
    invalidate_cloudfront
    
    echo
    log_success "Frontend deployment completed successfully!"
    log_info "Frontend URL: https://$DISTRIBUTION_DOMAIN"
    echo
    log_info "Next steps:"
    log_info "  1. Wait a few minutes for CloudFront to propagate changes"
    log_info "  2. Visit the frontend URL to verify deployment"
    log_info "  3. Check browser console for any configuration issues"
}

# Help function
show_help() {
    echo "Usage: $0 [ENVIRONMENT]"
    echo
    echo "Deploy the Travel Agent frontend to AWS S3 + CloudFront"
    echo
    echo "Arguments:"
    echo "  ENVIRONMENT    Environment name (default: dev)"
    echo
    echo "Examples:"
    echo "  $0              # Deploy to dev environment"
    echo "  $0 dev          # Deploy to dev environment"
    echo "  $0 staging      # Deploy to staging environment"
    echo "  $0 production   # Deploy to production environment"
    echo
    echo "Prerequisites:"
    echo "  - AWS CLI configured with appropriate credentials"
    echo "  - CDK stack deployed: cdk deploy TravelAgentStack-ENVIRONMENT"
    echo "  - Node.js and npm installed"
    echo "  - jq installed for JSON parsing"
}

# Check for help flag
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_help
    exit 0
fi

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    log_error "jq is not installed. Please install it first:"
    log_error "  macOS: brew install jq"
    log_error "  Ubuntu: sudo apt-get install jq"
    log_error "  CentOS: sudo yum install jq"
    exit 1
fi

# Run main function
main "$@"
